name: Moodle Automator

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 mins
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Main Script
        env:
          # Moodle
          MOODLE_USER: ${{ secrets.MOODLE_USER }}
          MOODLE_PASS: ${{ secrets.MOODLE_PASS }}
          
          # Telegram
          TELEGRAM_LINK: ${{ secrets.TELEGRAM_LINK }}

          # Account 1: Gmail (Also used as the visible "From" address)
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          
          # Account 2: Brevo 1
          # Login: 9dd3f5001@smtp-brevo.com
          BREVO_USER_1: ${{ secrets.BREVO_USER_1 }}
          BREVO_PASS_1: ${{ secrets.BREVO_PASS_1 }}
          
          # Account 3: Brevo 2
          # Login: 9c8009001@smtp-brevo.com
          BREVO_USER_2: ${{ secrets.BREVO_USER_2 }}
          BREVO_PASS_2: ${{ secrets.BREVO_PASS_2 }}
          
        run: python main.py

      - name: Commit State & History
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add history.txt bot_state.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update state" && git push)
